-- --------------------------------------------------------
-- 1. Create table for Likes
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blog_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(post_id, user_id)
);

-- Turn on RLS for Likes
ALTER TABLE public.blog_likes ENABLE ROW LEVEL SECURITY;

-- Policies for Likes
CREATE POLICY "Users can like a post" ON public.blog_likes
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can remove their own like" ON public.blog_likes
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Anyone can view likes" ON public.blog_likes
    FOR SELECT USING (true);


-- --------------------------------------------------------
-- 2. Create table for Saves (Bookmarks)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blog_saves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(post_id, user_id)
);

-- Turn on RLS for Saves
ALTER TABLE public.blog_saves ENABLE ROW LEVEL SECURITY;

-- Policies for Saves
CREATE POLICY "Users can save a post" ON public.blog_saves
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unsave a post" ON public.blog_saves
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own saves" ON public.blog_saves
    FOR SELECT USING (auth.uid() = user_id);


-- --------------------------------------------------------
-- 3. Create table for Comments
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL CHECK (char_length(content) > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn on RLS for Comments
ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;

-- Policies for Comments
CREATE POLICY "Users can insert comments" ON public.blog_comments
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can edit their own comments" ON public.blog_comments
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments" ON public.blog_comments
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Anyone can view comments" ON public.blog_comments
    FOR SELECT USING (true);

-- --------------------------------------------------------
-- 4. Enable realtime for the new tables (Optional but recommended)
-- --------------------------------------------------------
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE blog_likes;
ALTER PUBLICATION supabase_realtime ADD TABLE blog_comments;
