server {
    listen       8080;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Prevenir cacheo del index.html para asegurar que siempre se cargue la última versión
        if ($request_uri ~* ^/($|index\.html)) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }
    }

    # Proxy para Zoho para evitar problemas de CORS
    location /zoho-api/ {
        proxy_pass https://creatorapp.zohopublic.com/;
        proxy_set_header Host creatorapp.zohopublic.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    # Error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
