import { api } from './services/api';

async function test() {
  console.log('--- STARTING CRUD TEST ---');
  
  // 1. ADD
  const newAssoc = {
    name: 'TEST_AGENT',
    last_name: 'AI',
    email: `testagent_${Date.now()}@traveliz.example.com`,
    position: 'Tester',
    tipo: 'ASSOCIATE',
    Branch: 'ROBLE',
    content: 'Test content generated by AI',
    instagram: 'https://instagram.com/test',
    facebook: 'https://facebook.com/test',
    tik_tok: 'https://tiktok.com/@test',
    linkedIn: 'https://linkedin.com/in/test',
    image: 'https://example.com/image.jpg'
  };

  console.log('Adding associate...');
  try {
    const created = await api.upsertAssociate(newAssoc);
    if (!created) {
      console.log('Fail: Could not create associate (might be RLS restricted)');
      return;
    }
    console.log('Created successfully with ID:', created.id);

    // 2. EDIT
    console.log('Editing associate...');
    const editedAssoc = {
      ...created,
      position: 'Senior Tester',
      Branch: 'CDMX'
    };
    
    const updated = await api.upsertAssociate(editedAssoc);
    console.log('Updated successfully:', updated?.position === 'Senior Tester');

    // 3. DELETE
    console.log('Deleting associate...');
    const deleted = await api.deleteAssociate(created.id!);
    console.log('Deleted successfully:', deleted);
    
  } catch (e: any) {
    console.error('Error during testing:', e.message);
  }
}

test();
